os: linux
dist: xenial
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: YFFqFrcuQVtT5bVZFpOB8f67BY6sGc8f0gn/1gh1pWnQfNUrjCJpgUXXQmb/wkCwevgy+VLjRrRUm4RCunPr5UhZRczaujED6r1wbHCJAZlouG8fqbsMjOUFjBIYZlA4z/3uyzb2CoeRbxq70g7E9IoM3FCKV6zd834NU06g2cdQZL6LGDJ1g03Dj2BMVfE4hUpgkuW1KQ3oheoXlvb9OPuxEuP4BJVZcJp4BAQ9QfLDXO/bUr65/rcDaQ+bjEUn31hw1Zy69tB52EB21YIJ2wGfxy7Q5b5kErSCG5uY6iLgTpiYp5YQeWXod6BRqsi4dYx48LER7d5ZtEBi7f1EU3Bc0zdgmBbAu2/oAC3dwCAn3QFcQS2BSymGEMAwcaLjcMdfOLKh3nr5p1jZxBW6HEujK11Ow+WFtRz6AfVl6hp2pAdL2zbiwjYwXHmNJLqgRkXsXkCcm2PURadmgqT9gPPoitAVjRCD5VVroOhCfly/+iI9ADdmPEBi1FyfwNzvBFicorgj2RweSOHYwRf5EKGKA1OzuPiuI2+oOC8E2saMFo9i8eyXPXrZRtpMBO04dnvgSELQI6ExAlK9tM6rahhU2Y4AWZHea8iUnB5czt6Ur024fkJlEfRQvW/rNxu8vdENNWSYc+wqWi48IUD1urcjjVCjgd6EbDPatLpPoFg=
branches:
  only:
  - master
